from Crypto.Cipher import *

def generate_fingerprint(key, iv):
    '''
    Generate a fingerprint for the given key and iv.
    
    :param key: The key used for encryption.
    :param iv: The iv used for encryption.
    ''' # YOUR CODE HERE return fingerprint using SHA-256 hash function

def check_fingerprint(key, iv, fingerprint):
    '''
    Check if the given fingerprint matches the one generated by generate_fingerprint().
    
    :param key: The key used for encryption.
    :param iv: The iv used for encryption.
    :param fingerprint: The fingerprint to compare against.
    :return: True if the fingerprints match, False otherwise.
    ''' # YOUR CODE HERE 

def